# Dans ce sujet de TP, nous nous familiarisons avec numpy tout en révisant les notions d'algèbre linéaire et préparant les outils nécessaires à la résolutions de systèmes linéaires.

In [1]:
import numpy as np

### 1) Proposez une fonction de décomposition d'une matrice carrée A=L+D+U avec D la matrice diagonale constituée des éléments diagonaux de A, U et L des matrices triangulaires respectivement supérieure et inférieure dont les éléments diagonaux sont nuls.

In [12]:
def decomposition_matrice(A):
    n, m = A.shape
    if n != m:
        raise ValueError("La matrice A doit être carrée")
    
    D = np.diag(np.diag(A))
    L = np.array([[A[i, j] if i > j else 0 for j in range(n)] for i in range(n)])
    U = np.array([[A[i, j] if i < j else 0 for j in range(n)] for i in range(n)])

    return L, D, U

In [13]:
A = np.array([[1, 0, -1],
              [3, 1, 1],
              [1, 0, 1]])

In [14]:
L, D, U = decomposition_matrice(A)
L,D,U

(array([[0, 0, 0],
        [3, 0, 0],
        [1, 0, 0]]),
 array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]),
 array([[ 0,  0, -1],
        [ 0,  0,  1],
        [ 0,  0,  0]]))

### 2) Proposer une fonction calculant "manuellement" le produit de deux matrices. Comparez son temps d'exécution avec la méthode dot

In [ ]:
"""def produit_matrice(A, B):
    n, k = A.shape
    k, m = B.shape
    resultat = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            for l in range(k):
                resultat[i, j] += A[i, l] * B[l, j]
    return resultat"""

In [15]:
def produit_matrice(A, B):
    n, k = A.shape
    k, m = B.shape
    resultat = np.array([[sum(A[i, l] * B[l, j] for l in range(k)) for j in range(m)] for i in range(n)])
    return resultat

In [16]:
A = np.array([[1, 0, -1],
              [3, 1, 1],
              [1, 0, 1]])
B = np.array([[2, 4, 1],
              [3, 1, 0],
              [-1, 0, 2]])

In [17]:
print(produit_matrice(A,B))

[[ 3  4 -1]
 [ 8 13  5]
 [ 1  4  3]]


### 3) Proposer des fonctions permettant de renvoyer les matrices élémentaire suivantes :

#### a) La matrice Ti,j permettant la permutation des lignes i et j

In [23]:
import numpy as np

def permutation(n, i, j):

    P = np.eye(n)
    P[[i, j], :] = P[[j, i], :] 
    return P

#### b) La matrice Di(λ) permettant la multiplication de la ligne i par λ

In [24]:
def multiplication_ligne(n, i, lambda_):
    
    D = np.eye(n)
    D[i, i] = lambda_
    return D

#### c) La matrice Lr,s(λ) permettant d'ajouter à la ligne r, λ fois la ligne s

In [25]:
def addition_multiple_ligne(n, r, s, lambda_):
    
    L = np.eye(n)
    L[r, s] = lambda_
    return L

## Test

In [27]:
n = 3
i, j = 1, 2  
r, s = 0, 1 
lambda_ = 4
P = permutation(n, i, j)
D = multiplication_ligne(n, i, lambda_)
L = addition_multiple_ligne(n, r, s, lambda_)

P, D, L

(array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[1., 0., 0.],
        [0., 4., 0.],
        [0., 0., 1.]]),
 array([[1., 4., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

### 4) Vérifiez sur quelques exemples les informations données en cours concernant les matrices inverses des matrices précédentes

In [29]:
P_inv = P  
D_inv = multiplication_ligne(n, i, 1/lambda_)
L_inv = addition_multiple_ligne(n, r, s, -lambda_)
P_inv, D_inv, L_inv

(array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]),
 array([[1.  , 0.  , 0.  ],
        [0.  , 0.25, 0.  ],
        [0.  , 0.  , 1.  ]]),
 array([[ 1., -4.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]))

In [31]:
print(np.allclose(np.dot(P, P_inv), np.eye(n)))  
print(np.allclose(np.dot(D, D_inv), np.eye(n)))
print(np.allclose(np.dot(L, L_inv), np.eye(n))) 

True
True
True


### 5) Vérifiez que le produit A=Lr1,s(λ1)Lr2,s(λ2) donne une matrice identité à laquelle on ajoute λ1 sur Ar1, s et λ2 sur Ar2,s. 

In [1]:
import numpy as np

n = 4
r1, s = 2, 1
r2 = 3
lambda1 = 5
lambda2 = -3

I = np.eye(n)

Lr1_s_lambda1 = np.copy(I)
Lr1_s_lambda1[r1-1, s-1] = lambda1  

Lr2_s_lambda2 = np.copy(I)
Lr2_s_lambda2[r2-1, s-1] = lambda2 

product = np.dot(Lr2_s_lambda2, Lr1_s_lambda1)
product


array([[ 1.,  0.,  0.,  0.],
       [ 5.,  1.,  0.,  0.],
       [-3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### 6) Proposez deux écritures de génération de la matrice Mr((λr+1,…,λn))=Lr+1,r(λr+1)…Ln,r(λn).

In [2]:
import numpy as np

def generate_matrix_mr_direct(n, r, lambdas):
    M = np.eye(n)  
    
    for i in range(r+1, n):
        L = np.eye(n)
        L[i, r] = lambdas[i - (r+1)]  
        M = np.dot(L, M)  
    
    return M

In [4]:
n = 5  
r = 2 
lambdas = [3, -1, 4]  
matrix_mr_direct = generate_matrix_mr_direct(n, r, lambdas)
matrix_mr_direct

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  3.,  1.,  0.],
       [ 0.,  0., -1.,  0.,  1.]])

In [3]:
def generate_matrix_mr_incremental(n, r, lambdas):
    M = np.eye(n)  
    for i in range(r+1, n):
        M[i, r] = lambdas[i - (r+1)]
    
    return M


In [5]:
matrix_mr_incremental = generate_matrix_mr_incremental(n, r, lambdas)
matrix_mr_incremental

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  3.,  1.,  0.],
       [ 0.,  0., -1.,  0.,  1.]])